### ISSUE TITLE
Faz um tutorial de PHP também

### ISSUE THREAD

**Issue by horodeski** [marrcandre/django-drf-tutorial#15]

**Comment by GustavodePaulaGorges** [comment]
Save us Marcoandre.... Save us

**Comment by VictoorLDS** [comment]
Pfvr 😭😭😭😭🙏🙏🙏

**Comment by mariagerotti** [comment]
pedido dos seus alunos mais brilhantes e queridos😿😿😿 será uma honra seguir o seu tutorial de php😸

**Comment by horodeski** [comment]
Tem que ser puro :(

**Comment by marrcandre** [comment]
Dai complica :(

**Comment by horodeski** [comment]
Mas é uma ótima ideia... Vou tentar fazer pra praticar
