### ISSUE TITLE
Link 18 quebrado

### ISSUE THREAD

**Issue by jonatasperaza** [marrcandre/django-drf-tutorial#18]
O link a seguir mostra uma parte do tutorial pela qual voce precisa copiar a livraria.json

https://github.com/marrcandre/django-drf-tutorial/tree/versao-2023?tab=readme-ov-file#18-dump-e-load-de-dados

no tutorial ele referencia o seguinte link:

wget https://github.com/marrcandre/django-drf-tutorial/raw/main/scripts/livraria.json

Pórem o arquivo só esta disponivel na breanch de 2023 que ficaria assim:

https://github.com/marrcandre/django-drf-tutorial/raw/versao-2023/scripts/livraria.json

**Comment by marrcandre** [comment]
Corrigido. Obrigado pela correção.

Um abraço

Marco André


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
02/07/24,
10:03:52

Em sex., 28 de jun. de 2024 às 11:47, Jonatas Silva peraza <
***@***.***> escreveu:
